import {
  Box,
  ShoppingBag,
  BookText,
  Users,
  Settings,
  ChartBar,
  HousePlug,
  Cat,
  Gift,
} from 'lucide-react';

export const menuItems = [
  { id: 1, title: 'Dashboard', path: '/', icon: HousePlug },
  { id: 2, title: 'Products', path: '/product', icon: Box },
  { id: 8, title: 'Categories', path: '/category', icon: Cat },
  { id: 9, title: 'Brands', path: '/brand', icon: Gift },
  { id: 3, title: 'Orders', path: '/order', icon: ShoppingBag },
  { id: 4, title: 'Customers', path: '/customer', icon: Users },
  { id: 5, title: 'Inventory', path: '/inventory', icon: BookText },
  { id: 6, title: 'Analytics', path: '/analytic', icon: ChartBar },
  { id: 7, title: 'Settings', path: '/setting', icon: Settings },
];

export const baseUrl = import.meta.env.BASE_URL || 'http://localhost:3000';

export const formatDate = (dateString = '') => {
  const date = new Date(dateString);
  return date.toLocaleDateString('en-US', {
    month: 'short', // Nov
    day: '2-digit', // 28
    year: 'numeric', // 2023
  });
};

export const categories = [
  'beauty',
  'fragrances',
  'furniture',
  'groceries',
  'home-decoration',
  'kitchen-accessories',
  'laptops',
  'mens-shirts',
  'mens-shoes',
  'mens-watches',
  'mobile-accessories',
  'motorcycle',
  'skin-care',
  'smartphones',
  'sports-accessories',
  'sunglasses',
  'tablets',
  'tops',
  'vehicle',
  'womens-bags',
  'womens-dresses',
  'womens-jewellery',
  'womens-shoes',
  'womens-watches',
];

export const brands = [
  'Amazon',
  'Annibale Colombo',
  'Apple',
  'Asus',
  'Attitude',
  'Bath Trends',
  'Beats',
  'Calvin Klein',
  'Casual Comfort',
  'Chanel',
  'Chic Cosmetics',
  'Chrysler',
  'Classic Wear',
  'Comfort Trends',
  'Dell',
  'Dior',
  'Dodge',
  'Dolce & Gabbana',
  'Elegance Collection',
  'Essence',
  'Fashion Co.',
  'Fashion Diva',
  'Fashion Express',
  'Fashion Fun',
  'Fashion Gold',
  'Fashion Shades',
  'Fashion Timepieces',
  'Fashion Trends',
  'Fashionista',
  'Furniture Co.',
  'GadgetMaster',
  'Generic Motors',
  'Gigabyte',
  'Glamour Beauty',
  'Gucci',
  'Heshe',
  'Huawei',
  'IWC',
  'Kawasaki',
  'Knoll',
  'Lenovo',
  'Longines',
  'MotoGP',
  'Nail Couture',
  'Nike',
  'Off White',
  'Olay',
  'Oppo',
  'Pampi',
  'Prada',
  'ProVision',
  'Puma',
  'Realme',
  'Rolex',
  'Samsung',
  'ScootMaster',
  'SnapTech',
  'SpeedMaster',
  'TechGear',
  'Urban Chic',
  'Vaseline',
  'Velvet Touch',
  'Vivo',
];
