export const env = {
  port: process.env.PORT,
  host: process.env.HOST,
  cors: process.env.CORS,
  nodeEnv: process.env.NODE_ENV,
  mongodbURI: process.env.MONGODB_URI,
  secretToken: process.env.SECRET_TOKEN,
  clientURL: process.env.CLIENT_REDIRECT_URL,
  serverURL: process.env.SERVER_REDIRECT_URL,
  stripeApiKey: process.env.STRIPE_API_SECRET,
  stripeApiSecret: process.env.STRIPE_WEBHOOK_SECRET,
  googleClientID: process.env.GOOGLE_CLIENT_ID,
  googleClientSecret: process.env.GOOGLE_CLIENT_SECRET,
  githubClientID: process.env.GITHUB_CLIENT_ID,
  githubClientSecret: process.env.GITHUB_CLIENT_SECRET,
  awsAccessKey: process.env.AWS_ACCESS_KEY_ID,
  awsSecretKey: process.env.AWS_SECRET_ACCESS_KEY,
  awsRegion: process.env.AWS_REGION,
  awsBucketName: process.env.S3_BUCKET_NAME,
  mailtrapHost: process.env.MAILTRAP_SMTP_HOST,
  mailtrapPort: process.env.MAILTRAP_SMTP_PORT,
  mailtrapUser: process.env.MAILTRAP_SMTP_USER,
  mailtrapPass: process.env.MAILTRAP_SMTP_PASS,
  geminiApiKey: process.env.GEMINI_API_KEY,
  clipDropApiKey: process.env.CLIPDROP_API_KEY,
};
